[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# SPA Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# MIME Type Headers - Critical for JavaScript modules
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript;charset=utf-8"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript;charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css;charset=utf-8"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "text/javascript;charset=utf-8"
    Cache-Control = "public,max-age=31536000,immutable"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css;charset=utf-8"
    Cache-Control = "public,max-age=31536000,immutable"

# Security Headers without unsafe-eval
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1;mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https:; media-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self';"

# HTML Caching
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public,max-age=3600"
    Content-Type = "text/html;charset=utf-8"